# Generated by Django 4.0.4 on 2022-04-27 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20220128_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 27, 22, 11, 40, 500523)),
        ),
    ]
