# Generated by Django 4.0.4 on 2022-04-27 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_contacts_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 27, 22, 24, 20, 255031)),
        ),
    ]
