# Generated by Django 3.0.7 on 2022-01-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=255)),
                ('l_name', models.CharField(max_length=255)),
                ('Designation', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='photos/%y/%m/%d/')),
                ('facebook', models.URLField(max_length=255)),
                ('google', models.URLField(max_length=255)),
                ('twitter', models.URLField(max_length=255)),
                ('email', models.EmailField(default='', max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
