# Generated by Django 3.0.7 on 2022-01-18 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=500)),
                ('car_color', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('year', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)])),
                ('state', models.CharField(choices=[('pu', 'punjab'), ('bl', 'blochistan'), ('kpk', 'khaibar'), ('snd', 'sind')], max_length=30)),
                ('condition', models.CharField(max_length=255)),
                ('features', models.CharField(choices=[('powerstairing', 'powerstairing'), ('powerwindow', 'powerwindow'), ('powelockes', 'powerlokes'), ('powermirror', 'powermirror')], max_length=30)),
                ('car_photo', models.ImageField(upload_to='photos/%y/%m/%d/')),
                ('car_photo1', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('car_photo2', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('car_photo3', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('car_photo4', models.ImageField(blank=True, upload_to='photos/%y/%m/%d/')),
                ('price', models.IntegerField()),
                ('bode_style', models.CharField(max_length=30)),
                ('engine', models.CharField(max_length=30)),
                ('transmision', models.CharField(max_length=30)),
                ('interior', models.CharField(max_length=30)),
                ('passengers', models.CharField(max_length=30)),
                ('miles', models.IntegerField()),
                ('Dores', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')])),
                ('fuel_type', models.CharField(max_length=30)),
                ('Number_owner', models.CharField(max_length=30)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
