# Generated by Django 3.0.7 on 2022-01-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20220118_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='carteam',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
